#!/usr/bin/bash
chmod -x /etc/update-motd.d/10-help-text /etc/update-motd.d/91-release-upgrade
sed -i -r 's/^#?ENABLED=.*/ENABLED=0/' /etc/default/motd-news
sed -i -r 's/^#?X11Forwarding .*/X11Forwarding no/' /etc/ssh/sshd_config
sed -i -r 's/^#?Prompt=.*/Prompt=never/' /etc/update-manager/release-upgrades
sed -i -r 's/^#?RemoveIPC=.*/RemoveIPC=no/' /etc/systemd/logind.conf
echo "set enable-bracketed-paste 0" >> /etc/inputrc
systemctl mask esm-cache.service
fallocate -l 512M /swapfile
chmod 600 /swapfile
mkswap /swapfile
echo '/swapfile none swap sw 0 0' >> /etc/fstab
if [ ! -f /home/ubuntu/.ssh/authorized_keys ]; then curl -sS https://github.com/dogsbody.keys -o /home/ubuntu/.ssh/authorized_keys; fi
chown ubuntu:ubuntu -R /home/ubuntu
